module.exports = {
	WALL: 'wall',
	FLOOR: 'floor',
	FLOOR_2: 'floor2',
	GRASS_1: 'grass1',
	GRASS_2: 'grass2',
	TREE: 'tree',
	DOOR: 'door',
	CROSS_WINDOW: 'crossWindow',
	FOUNTAIN: 'fountain',
	WATER: 'water',
	WELL: 'well',
	DIRT: 'dirt',
	FIREPLACE: 'fireplace',
	COLUMN: 'column',
	R_TORCH: 'rTorch',
	L_TORCH: 'lTorch',
	THRONE: 'throne',
	ORB: 'orb',
	SMALL_TABLE: 'smallTable',
	MAGIC_CARPET: 'magicCarpet',
	BED_1: 'bed1',
	BED_2: 'bed2',
	LOCKER: 'locker'
};